### ISSUE TITLE
migrated content

### ISSUE THREAD

**Issue by amcguire62** [OCHA-DAP/wordpress-centre-theme#2]
We have an issue with migrated content ... its currently formatting differently on the new blog. See following examples ... 
![screen shot 2017-04-04 at 19 07 58](https://cloud.githubusercontent.com/assets/1962335/24671643/2c690864-196a-11e7-898c-8622ec901bda.png)
![screen shot 2017-04-04 at 18 48 35](https://cloud.githubusercontent.com/assets/1962335/24671644/2c6bc9e6-196a-11e7-9fb7-cd9ca30b96d1.png)
![screen shot 2017-04-04 at 18 57 44](https://cloud.githubusercontent.com/assets/1962335/24671645/2c728736-196a-11e7-9ff3-8228f1d22a71.png)
![screen shot 2017-04-04 at 19 05 25](https://cloud.githubusercontent.com/assets/1962335/24671646/2c75fe5c-196a-11e7-8188-a85701954586.png)
![screen shot 2017-04-04 at 18 57 32](https://cloud.githubusercontent.com/assets/1962335/24671647/2c76578a-196a-11e7-8549-719e51b12a44.png)
![screen shot 2017-04-04 at 19 05 36](https://cloud.githubusercontent.com/assets/1962335/24671648/2c7dc9c0-196a-11e7-9c55-c67f15b9956b.png)

**Comment by beckybjain** [comment]
Some posts don't have images imported & text formatting is off. [For example](https://centre.humdata.org/wp-admin/edit.php?s&post_status=all&post_type=post&action=-1&m=0&cat=98&filter_action=Filter&paged=1&action2=-1):

![image](https://cloud.githubusercontent.com/assets/26910269/24678654/656684ea-1959-11e7-9282-5195b4a319f6.png)

**Comment by baripembo** [comment]
I added a function that will strip out inline styles in post content -- this should help some of the formatting issues (Becky, this fixes your width issue in the Haiti post). There are still some styles in the migrated posts that we will need to manually override. I also need to check with Yumi on some things like how lists should look, etc.

**Comment by baripembo** [comment]
I went through all 98 posts in WP and made text formatting updates. There were 4 blog posts left that had issues with charts -- these posts were put into draft mode.
