### ISSUE TITLE
Images >1MB

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/wordpress-centre-theme#4]
I noticed that our blog page has a big size. There are some images that are more than 1MB which slow us a lot.
Gzipped compression is up and running ok.

![screen shot 2017-04-05 at 10 52 25](https://cloud.githubusercontent.com/assets/3865844/24695395/43a42304-19ee-11e7-94b8-88dd76ece14e.png)

**Comment by baripembo** [comment]
I've compressed and re-uploaded the 7 images that were over 1MB, now under 200KB each. Will make recommendation to content people to compress images before uploading.
