### ISSUE TITLE
"Show more" link is missing 

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/wordpress-centre-theme#6]
How to reproduce:
1. filter by video - loads 2 video thumbnails (one is not loading)
2. click on "Load More" - it will try to load and then it will dissapear (no load more button)
3. filter by any other criteria (all, blog, etc) - "Load more" is still missing

**Comment by baripembo** [comment]
I am not able to reproduce this error -- are you still seeing this? I noticed that the Mixpanel CORS error that I logged earlier this week has gone away. Maybe that error was causing other scripts to fail?
